### ISSUE TITLE
int vs float in data

### ISSUE THREAD

**Issue by boryana-ilieva** [OpenSourceEconomics/soepy#104]
Make sure that int and float columns are implemented correctly in the simulated data frame.

@boryana-ilieva , here is what I had in mind for the missing data. Please see if this fits. https://pandas.pydata.org/pandas-docs/stable/user_guide/integer_na.html#integer-na

_Originally posted by @peisenha in https://github.com/OpenSourceEconomics/soepy/pull/92#issuecomment-590350211_

**Comment by peisenha** [comment]
This is done.
