### ISSUE TITLE
Enhancements taxes and transfers

### ISSUE THREAD

**Issue by boryana-ilieva** [OpenSourceEconomics/soepy#144]
To do:

- [x] add childcare costs
- [x] subtract 35% of of last period wage when calculating ALG I and elterngeld
- [x] try using chosen last period hours when calculating ALG I and elterngeld(currently using potential full-time wage, i.e. full-time hours)
- [x] change housing to 77,5 as in text

**Comment by MaxBlesch** [comment]
Will be done in #146

**Comment by MaxBlesch** [comment]
Done!
