### ISSUE TITLE
horizontal entries for coefficients values and their labels

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/soepy#22]
https://github.com/OpenSourceEconomics/soepy/blob/8f32fa2573ae1b17a39651d01021845a561bebc6/doc/tutorial/toy_model_init_file_1000.yml#L19-L50

Can we please have horizontal entries, so the label is clearly mapped to the value?

**Comment by boryana-ilieva** [comment]
Do we also want to have some grouping or nesting of the coefficients on top of introducing horizontal entries in the ini file?

What I mean is that, in the current setup, moving the coefficient from an ini file with horizontal entries to the named tuple would entail:

model_params.optim_paras = list(init_dict["PARAMETERS"].values())

such that model.params.optim_paras is a list of ca. 18 coefficients. In subsequent functions, we than have calls like: 

    gamma_s0 = np.dot(educ_level, model_params.optim_paras[0:3])
    gamma_s1 = np.dot(educ_level, model_params.optim_paras[3:6])

which we agree is suboptimal.

@peisenha , could we discuss wether we should and how we could add groupings or labels of some sort?

**Comment by peisenha** [comment]
Yes, I think we should move towards `model_params.optim_paras['gamma_0s'][:3]` type of accessing. Thus combining label and position based access. However, I also add this issue to the agenda of our call next week.

**Comment by boryana-ilieva** [comment]
In this case, my proposal is to implement nested namedtuple, i.e., `model_params.optim_paras.gamma_0s[:3]` 

Main motivation is the fact that numba cannot work with dictionaries. We won't be able to do numba magic, if we nest a dictionary in the namedtuple.

**Comment by peisenha** [comment]
I changed my mind, please do not use the nested attribute structure as this already implies a logic link between the optimization routine that we build outside the package and works across packages. Please just do `model_params.gamma_0s`instead. Let me know if you have any questions.

**Comment by boryana-ilieva** [comment]
In this case I have a question concerning how the interface of the objective function in the smm routine should look like.

Currently it is `def get_objective (init_file_name, moments_obs, weighting_matrix, optim_paras):` and we set the first three inputs using partial. The last argument is the summary of all gammas, deltas, and so on, i.e., everything we are estimating by smm. https://github.com/boryana-ilieva/smm_soepy/blob/master/smm/objective.py

If I were to omit the nesting and thus `optim_paras`, the objective would become a function of all these (currently 18) parameters which is not nice, I think.

If I were to make the objective a function of the whole named tuple `model_params`, I would still have to separate the parameters that are to be estimated from the parameters governing the model setup, like number of periods and number of agents and the estimation process, like the seeds, somehow inside the objective.

So, I feel that we still need some summary object of all parameters we are estimating in the smm routine. How do you propose we solve this?

**Comment by peisenha** [comment]
We just discussed this over the phone, so just let me know if any further questions arise during the refactoring.
