### ISSUE TITLE
turn off DeprecationWarnings from matplotlib

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/soepy#29]
============================================================================================= warnings summary =============================================================================================
/home/peisenha/.local/share/anaconda3/lib/python3.7/site-packages/matplotlib/rcsetup.py:20: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, Mapping

/home/peisenha/.local/share/anaconda3/lib/python3.7/site-packages/matplotlib/colors.py:53: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Sized

/home/peisenha/.local/share/anaconda3/lib/python3.7/site-packages/yaml/constructor.py:126: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if not isinstance(key, collections.Hashable):

-- Docs: https://docs.pytest.org/en/latest/warnings.html

**Comment by peisenha** [comment]
At this point, we simply turn off all DepreciationWarnings during py.test. However, going forward we want to be more selective. For example, only turn them off during PRODUCTION. This requires us to set up the DEBUG / PRODUCTION distinction in the package. We will discuss this later.

**Comment by MaxBlesch** [comment]
Outdated
