### ISSUE TITLE
refactor education level assignment

### ISSUE THREAD

**Issue by boryana-ilieva** [OpenSourceEconomics/soepy#36]
We want to revisit the assignment of levels of education based on the years of education the individuals in the data have completed.

Note:
In order to speed up regression tests and ensure that robustness tests are running properly at the same time, we reduced the years of education in the simulated data from 14 to 12. For this value, the only education levels now observed in the data frame is low [1,0,0].

**Comment by boryana-ilieva** [comment]
@peisenha , I would suggest that we also include this one in the upgrade of testing infrastructure PR. What do you think?

**Comment by peisenha** [comment]
Yes, please propose a possible solution that allows us to maintain a regression test vault with many fast models.

**Comment by boryana-ilieva** [comment]
Resolved by #35
