### ISSUE TITLE
greetings from @sebecker

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/soepy#38]
![Screenshot from 2019-03-20 16-13-16](https://user-images.githubusercontent.com/3607591/54695904-20f33f00-4b2b-11e9-8982-1761f41bc1ca.png)

What is this? Can we turn it off?

**Comment by SeBecker** [comment]
I have to admit that I don't know. Since I haven't deleted any comments manually I assume that codacy used the permission i provided them. I would appreciate if you would let me know if somethins like this will also happen in upcoming PRs.

**Comment by peisenha** [comment]
@boryana-ilieva , please work on this with @SeBecker  when you have a chance ...

**Comment by peisenha** [comment]
Appears to use the permissions to modify outdated codacy complaints. Let's just ignore this ...
