### ISSUE TITLE
setattr to set attr with string

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/soepy#41]
This code 

https://github.com/OpenSourceEconomics/soepy/blob/3b21659d117b4ae8a8fdcd3e40f61de368184ff5/soepy/python/pre_processing/model_processing.py#L40-L60

can be easily replaced by 

```
    for group in init_dict.keys():
        for label in init_dict[group].keys():
            setattr(model_params, label,  init_dict[group][label])
```

**Comment by boryana-ilieva** [comment]
I rewrote the entire create_namedtuple function in PR #35 so this is no longer valid. Could we close?

**Comment by peisenha** [comment]
B-E-A-U-T-I-F-U-L
