### ISSUE TITLE
ose_utils

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/soepy#44]
Integrate use of  `ose_utils` library for in testing harness.

**Comment by peisenha** [comment]
@SeBecker, we will set this up as your next PR. I want you to take ownership of the development of the `ose_utils` package going forward.

**Comment by SeBecker** [comment]
Alright. I am looking forward to this.

**Comment by peisenha** [comment]
See https://github.com/OpenSourceEconomics/norpy/blob/master/development/tests/regression/run.py for an example, please create a new branch in  `ose_utils`.

**Comment by peisenha** [comment]
This did not really catch on ...
