### ISSUE TITLE
depenency file for PyCharm inspection

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/soepy#53]
Please configure environment.yml for our inspections of the dependencies. Otherwise, it always looks in `setup.py` and throws numerous warnings https://www.jetbrains.com/help/pycharm/managing-dependencies.html

**Comment by boryana-ilieva** [comment]
@peisenha unfortunately PyCharm seems to not be able to read the dependencies from the yml file. If we want to get rid of the package requirements warnings, we need to add a requirements.txt

Do we want that?

**Comment by peisenha** [comment]
@boryana-ilieva , all works fine if I configure it manually for my local machine. So, no, this is not worth any duplication.
