### ISSUE TITLE
doctest

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/soepy#57]
@boryana-ilieva created some doctests, @SeBecker please find out and implement their test in our testing workflow. https://docs.python.org/2/library/doctest.html

**Comment by SeBecker** [comment]
This is done, or?

**Comment by peisenha** [comment]
Yes, please use https://help.github.com/en/articles/closing-issues-using-keywords in your commit messages. Then this is taken care of automatically when mergin the PR.
