### ISSUE TITLE
Fix PR testing

### ISSUE THREAD

**Issue by boryana-ilieva** [OpenSourceEconomics/soepy#85]
Regression tests in PR testing battery currently not running due to inconsistency in function interfaces

**Comment by boryana-ilieva** [comment]
Find attached the error message from property.soepy.info after running pr testing.

Issue is that the regression test function requires an input - the number of regression tests to be ran: [https://github.com/OpenSourceEconomics/soepy/blob/master/soepy/test/test_regression.py#L9](url)

At the same time the function which collects all tests for property testing relies on the fact all test functions have the same interface, namely, they do not require inputs: [https://github.com/OpenSourceEconomics/soepy/blob/master/development/tests/property/property_auxiliary.py#L45](url)

![error_prop_reg](https://user-images.githubusercontent.com/17124076/70643739-d037ef00-1c41-11ea-8c04-9215b4bd967d.PNG)

**Comment by peisenha** [comment]
This function is not doing what the docstring is saying. It just runs the first ten tests. Just remove the parameterization and `idx` as an input argument and draw a random sample of five tests within the function.
