### ISSUE TITLE
travis notifications

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/soepy#96]
Please configure the notifications so that you are informed about failing builds.

**Comment by boryana-ilieva** [comment]
I have e-mails on for travis in general, I guess notifications are turned off for soepy on travis in general. I do not have permissions to enter the settings for soepy on travis.

**Comment by peisenha** [comment]
https://docs.travis-ci.com/user/notifications/#configuring-email-notifications

**Comment by boryana-ilieva** [comment]
Thanks
