### ISSUE TITLE
MANIFEST.in

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/soepy#99]
Do we still need this? This is probably a leftover from our conda exploration. There appear other artifacts as well such as the package install from conda in travis.

**Comment by boryana-ilieva** [comment]
Sorry, which line in travis do you mean e.g.? Probably I am too tired, I do not see which one you mean right now

**Comment by peisenha** [comment]
Thanks for checking back, guess we already removed the conda install. Can we then get rid of `soepy` on https://anaconda.org/OpenSourceEconomics/soepy ?

**Comment by boryana-ilieva** [comment]
Yes sure. I believe I do not have permissions to do it myself as a collaborator only. Please feel free to delete yourself and close the issue.

**Comment by peisenha** [comment]
I deleted it.
